---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SSViewer:
  theme: 'simple'
Debug:
  friendly_error_httpcode: true

---
Name: mytextextraction
After:
  - '#mysite'
  - '#textextraction'
---
Injector:
  FileTextCache: FileTextCache_SSCache

FileTextCache_SSCache:
  lifetime: 3600 # Number of seconds to cache content for

# Extract file contents from all File-objects
File:
  extensions:
    - FileTextExtractable
