language: php

sudo: false

addons:
  apt:
    packages:
      - tidy

addons:
  firefox: "31.0"

env:
  global:
    - CORE_RELEASE=3

php:
  - '5.6'

before_script:
 - composer self-update || true
 - phpenv rehash
 - phpenv config-rm xdebug.ini
 - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
 - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss

script:
 - vendor/bin/phpunit

